language: objective-c
osx_image: xcode9
group: "stable"
dist: "osx"
os: "osx"
env:
  global:
    - DESTINATION="arch=x86_64"
    - XCODE_SCHEME="PactMacOSExampleTests"
    - XCODE_PROJECT="PactMacOSExample.xcodeproj"
before_install:
  - gem install pact-mock_service -v 2.1.0
  - bundle install
  - brew update
  - carthage checkout
before_script:
  - carthage bootstrap --platform macOS
  - mkdir -p "./tmp"
  - pact-mock-service start --pact-specification-version 2.0.0 --log "./tmp/pact.log" --pact-dir "./tmp/pacts" -p 1234
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project $XCODE_PROJECT -scheme "$XCODE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO test -enableCodeCoverage YES | xcpretty -tc;
after_script:
  - pact-mock-service stop
