language: objective-c
osx_image: xcode9
before_install:
  - scripts/import_keychain.sh
  - security find-identity -v -p codesigning
  - gem install pact-mock_service -v 2.1.0
  - bundle install
  - brew update
  - brew upgrade
  - brew prune
  - brew cleanup
  - brew doctor
  - carthage checkout
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - carthage build --platform macOS
  - xcodebuild -project PactMacOSExample.xcodeproj -scheme "PactMacOSExample" -destination "arch=x86_64" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
